/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace OrderTypes {
  export type TakerOrderStruct = {
    isOrderAsk: PromiseOrValue<boolean>;
    taker: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    tokenId: PromiseOrValue<BigNumberish>;
    minPercentageToAsk: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
  };

  export type TakerOrderStructOutput = [
    boolean,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    isOrderAsk: boolean;
    taker: string;
    price: BigNumber;
    tokenId: BigNumber;
    minPercentageToAsk: BigNumber;
    params: string;
  };

  export type MakerOrderStruct = {
    isOrderAsk: PromiseOrValue<boolean>;
    signer: PromiseOrValue<string>;
    collection: PromiseOrValue<string>;
    price: PromiseOrValue<BigNumberish>;
    tokenId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    strategy: PromiseOrValue<string>;
    currency: PromiseOrValue<string>;
    nonce: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    minPercentageToAsk: PromiseOrValue<BigNumberish>;
    params: PromiseOrValue<BytesLike>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type MakerOrderStructOutput = [
    boolean,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    number,
    string,
    string
  ] & {
    isOrderAsk: boolean;
    signer: string;
    collection: string;
    price: BigNumber;
    tokenId: BigNumber;
    amount: BigNumber;
    strategy: string;
    currency: string;
    nonce: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    minPercentageToAsk: BigNumber;
    params: string;
    v: number;
    r: string;
    s: string;
  };
}

export interface MintedExchangeInterface extends utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "WETH()": FunctionFragment;
    "cancelAllOrdersForSender(uint256)": FunctionFragment;
    "cancelMultipleMakerOrders(uint256[])": FunctionFragment;
    "currencyManager()": FunctionFragment;
    "executionManager()": FunctionFragment;
    "isUserOrderNonceExecutedOrCancelled(address,uint256)": FunctionFragment;
    "matchAskWithTakerBid((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "matchAskWithTakerBidUsingETHAndWETH((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "matchBidWithTakerAsk((bool,address,uint256,uint256,uint256,bytes),(bool,address,address,uint256,uint256,uint256,address,address,uint256,uint256,uint256,uint256,bytes,uint8,bytes32,bytes32))": FunctionFragment;
    "owner()": FunctionFragment;
    "protocolFeeRecipient()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltyFeeManager()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "transferSelectorNFT()": FunctionFragment;
    "updateCurrencyManager(address)": FunctionFragment;
    "updateExecutionManager(address)": FunctionFragment;
    "updateProtocolFeeRecipient(address)": FunctionFragment;
    "updateRoyaltyFeeManager(address)": FunctionFragment;
    "updateTransferSelectorNFT(address)": FunctionFragment;
    "userMinOrderNonce(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOMAIN_SEPARATOR"
      | "WETH"
      | "cancelAllOrdersForSender"
      | "cancelMultipleMakerOrders"
      | "currencyManager"
      | "executionManager"
      | "isUserOrderNonceExecutedOrCancelled"
      | "matchAskWithTakerBid"
      | "matchAskWithTakerBidUsingETHAndWETH"
      | "matchBidWithTakerAsk"
      | "owner"
      | "protocolFeeRecipient"
      | "renounceOwnership"
      | "royaltyFeeManager"
      | "transferOwnership"
      | "transferSelectorNFT"
      | "updateCurrencyManager"
      | "updateExecutionManager"
      | "updateProtocolFeeRecipient"
      | "updateRoyaltyFeeManager"
      | "updateTransferSelectorNFT"
      | "userMinOrderNonce"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelAllOrdersForSender",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelMultipleMakerOrders",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "currencyManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "matchAskWithTakerBid",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "matchAskWithTakerBidUsingETHAndWETH",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "matchBidWithTakerAsk",
    values: [OrderTypes.TakerOrderStruct, OrderTypes.MakerOrderStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyFeeManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferSelectorNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCurrencyManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExecutionManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocolFeeRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyFeeManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTransferSelectorNFT",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "userMinOrderNonce",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAllOrdersForSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelMultipleMakerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserOrderNonceExecutedOrCancelled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchAskWithTakerBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchAskWithTakerBidUsingETHAndWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchBidWithTakerAsk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyFeeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSelectorNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCurrencyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExecutionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyFeeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTransferSelectorNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMinOrderNonce",
    data: BytesLike
  ): Result;

  events: {
    "CancelAllOrders(address,uint256)": EventFragment;
    "CancelMultipleOrders(address,uint256[])": EventFragment;
    "NewCurrencyManager(address)": EventFragment;
    "NewExecutionManager(address)": EventFragment;
    "NewProtocolFeeRecipient(address)": EventFragment;
    "NewRoyaltyFeeManager(address)": EventFragment;
    "NewTransferSelectorNFT(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RoyaltyPayment(address,uint256,address,address,uint256)": EventFragment;
    "TakerAsk(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)": EventFragment;
    "TakerBid(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelAllOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelMultipleOrders"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewCurrencyManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewExecutionManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFeeRecipient"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewRoyaltyFeeManager"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTransferSelectorNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerAsk"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerBid"): EventFragment;
}

export interface CancelAllOrdersEventObject {
  user: string;
  newMinNonce: BigNumber;
}
export type CancelAllOrdersEvent = TypedEvent<
  [string, BigNumber],
  CancelAllOrdersEventObject
>;

export type CancelAllOrdersEventFilter = TypedEventFilter<CancelAllOrdersEvent>;

export interface CancelMultipleOrdersEventObject {
  user: string;
  orderNonces: BigNumber[];
}
export type CancelMultipleOrdersEvent = TypedEvent<
  [string, BigNumber[]],
  CancelMultipleOrdersEventObject
>;

export type CancelMultipleOrdersEventFilter =
  TypedEventFilter<CancelMultipleOrdersEvent>;

export interface NewCurrencyManagerEventObject {
  currencyManager: string;
}
export type NewCurrencyManagerEvent = TypedEvent<
  [string],
  NewCurrencyManagerEventObject
>;

export type NewCurrencyManagerEventFilter =
  TypedEventFilter<NewCurrencyManagerEvent>;

export interface NewExecutionManagerEventObject {
  executionManager: string;
}
export type NewExecutionManagerEvent = TypedEvent<
  [string],
  NewExecutionManagerEventObject
>;

export type NewExecutionManagerEventFilter =
  TypedEventFilter<NewExecutionManagerEvent>;

export interface NewProtocolFeeRecipientEventObject {
  protocolFeeRecipient: string;
}
export type NewProtocolFeeRecipientEvent = TypedEvent<
  [string],
  NewProtocolFeeRecipientEventObject
>;

export type NewProtocolFeeRecipientEventFilter =
  TypedEventFilter<NewProtocolFeeRecipientEvent>;

export interface NewRoyaltyFeeManagerEventObject {
  royaltyFeeManager: string;
}
export type NewRoyaltyFeeManagerEvent = TypedEvent<
  [string],
  NewRoyaltyFeeManagerEventObject
>;

export type NewRoyaltyFeeManagerEventFilter =
  TypedEventFilter<NewRoyaltyFeeManagerEvent>;

export interface NewTransferSelectorNFTEventObject {
  transferSelectorNFT: string;
}
export type NewTransferSelectorNFTEvent = TypedEvent<
  [string],
  NewTransferSelectorNFTEventObject
>;

export type NewTransferSelectorNFTEventFilter =
  TypedEventFilter<NewTransferSelectorNFTEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RoyaltyPaymentEventObject {
  collection: string;
  tokenId: BigNumber;
  royaltyRecipient: string;
  currency: string;
  amount: BigNumber;
}
export type RoyaltyPaymentEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber],
  RoyaltyPaymentEventObject
>;

export type RoyaltyPaymentEventFilter = TypedEventFilter<RoyaltyPaymentEvent>;

export interface TakerAskEventObject {
  orderHash: string;
  orderNonce: BigNumber;
  taker: string;
  maker: string;
  strategy: string;
  currency: string;
  collection: string;
  tokenId: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type TakerAskEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  TakerAskEventObject
>;

export type TakerAskEventFilter = TypedEventFilter<TakerAskEvent>;

export interface TakerBidEventObject {
  orderHash: string;
  orderNonce: BigNumber;
  taker: string;
  maker: string;
  strategy: string;
  currency: string;
  collection: string;
  tokenId: BigNumber;
  amount: BigNumber;
  price: BigNumber;
}
export type TakerBidEvent = TypedEvent<
  [
    string,
    BigNumber,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ],
  TakerBidEventObject
>;

export type TakerBidEventFilter = TypedEventFilter<TakerBidEvent>;

export interface MintedExchange extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MintedExchangeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    WETH(overrides?: CallOverrides): Promise<[string]>;

    cancelAllOrdersForSender(
      minNonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<[string]>;

    executionManager(overrides?: CallOverrides): Promise<[string]>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<[string]>;

    updateCurrencyManager(
      _currencyManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateExecutionManager(
      _executionManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  WETH(overrides?: CallOverrides): Promise<string>;

  cancelAllOrdersForSender(
    minNonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelMultipleMakerOrders(
    orderNonces: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currencyManager(overrides?: CallOverrides): Promise<string>;

  executionManager(overrides?: CallOverrides): Promise<string>;

  isUserOrderNonceExecutedOrCancelled(
    user: PromiseOrValue<string>,
    orderNonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  matchAskWithTakerBid(
    takerBid: OrderTypes.TakerOrderStruct,
    makerAsk: OrderTypes.MakerOrderStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  matchAskWithTakerBidUsingETHAndWETH(
    takerBid: OrderTypes.TakerOrderStruct,
    makerAsk: OrderTypes.MakerOrderStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  matchBidWithTakerAsk(
    takerAsk: OrderTypes.TakerOrderStruct,
    makerBid: OrderTypes.MakerOrderStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  royaltyFeeManager(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferSelectorNFT(overrides?: CallOverrides): Promise<string>;

  updateCurrencyManager(
    _currencyManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateExecutionManager(
    _executionManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateProtocolFeeRecipient(
    _protocolFeeRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyFeeManager(
    _royaltyFeeManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateTransferSelectorNFT(
    _transferSelectorNFT: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  userMinOrderNonce(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    WETH(overrides?: CallOverrides): Promise<string>;

    cancelAllOrdersForSender(
      minNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    currencyManager(overrides?: CallOverrides): Promise<string>;

    executionManager(overrides?: CallOverrides): Promise<string>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<string>;

    updateCurrencyManager(
      _currencyManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateExecutionManager(
      _executionManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "CancelAllOrders(address,uint256)"(
      user?: PromiseOrValue<string> | null,
      newMinNonce?: null
    ): CancelAllOrdersEventFilter;
    CancelAllOrders(
      user?: PromiseOrValue<string> | null,
      newMinNonce?: null
    ): CancelAllOrdersEventFilter;

    "CancelMultipleOrders(address,uint256[])"(
      user?: PromiseOrValue<string> | null,
      orderNonces?: null
    ): CancelMultipleOrdersEventFilter;
    CancelMultipleOrders(
      user?: PromiseOrValue<string> | null,
      orderNonces?: null
    ): CancelMultipleOrdersEventFilter;

    "NewCurrencyManager(address)"(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;
    NewCurrencyManager(
      currencyManager?: PromiseOrValue<string> | null
    ): NewCurrencyManagerEventFilter;

    "NewExecutionManager(address)"(
      executionManager?: PromiseOrValue<string> | null
    ): NewExecutionManagerEventFilter;
    NewExecutionManager(
      executionManager?: PromiseOrValue<string> | null
    ): NewExecutionManagerEventFilter;

    "NewProtocolFeeRecipient(address)"(
      protocolFeeRecipient?: PromiseOrValue<string> | null
    ): NewProtocolFeeRecipientEventFilter;
    NewProtocolFeeRecipient(
      protocolFeeRecipient?: PromiseOrValue<string> | null
    ): NewProtocolFeeRecipientEventFilter;

    "NewRoyaltyFeeManager(address)"(
      royaltyFeeManager?: PromiseOrValue<string> | null
    ): NewRoyaltyFeeManagerEventFilter;
    NewRoyaltyFeeManager(
      royaltyFeeManager?: PromiseOrValue<string> | null
    ): NewRoyaltyFeeManagerEventFilter;

    "NewTransferSelectorNFT(address)"(
      transferSelectorNFT?: PromiseOrValue<string> | null
    ): NewTransferSelectorNFTEventFilter;
    NewTransferSelectorNFT(
      transferSelectorNFT?: PromiseOrValue<string> | null
    ): NewTransferSelectorNFTEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RoyaltyPayment(address,uint256,address,address,uint256)"(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      royaltyRecipient?: PromiseOrValue<string> | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaymentEventFilter;
    RoyaltyPayment(
      collection?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null,
      royaltyRecipient?: PromiseOrValue<string> | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaymentEventFilter;

    "TakerAsk(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)"(
      orderHash?: null,
      orderNonce?: null,
      taker?: PromiseOrValue<string> | null,
      maker?: PromiseOrValue<string> | null,
      strategy?: PromiseOrValue<string> | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerAskEventFilter;
    TakerAsk(
      orderHash?: null,
      orderNonce?: null,
      taker?: PromiseOrValue<string> | null,
      maker?: PromiseOrValue<string> | null,
      strategy?: PromiseOrValue<string> | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerAskEventFilter;

    "TakerBid(bytes32,uint256,address,address,address,address,address,uint256,uint256,uint256)"(
      orderHash?: null,
      orderNonce?: null,
      taker?: PromiseOrValue<string> | null,
      maker?: PromiseOrValue<string> | null,
      strategy?: PromiseOrValue<string> | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerBidEventFilter;
    TakerBid(
      orderHash?: null,
      orderNonce?: null,
      taker?: PromiseOrValue<string> | null,
      maker?: PromiseOrValue<string> | null,
      strategy?: PromiseOrValue<string> | null,
      currency?: null,
      collection?: null,
      tokenId?: null,
      amount?: null,
      price?: null
    ): TakerBidEventFilter;
  };

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    WETH(overrides?: CallOverrides): Promise<BigNumber>;

    cancelAllOrdersForSender(
      minNonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currencyManager(overrides?: CallOverrides): Promise<BigNumber>;

    executionManager(overrides?: CallOverrides): Promise<BigNumber>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferSelectorNFT(overrides?: CallOverrides): Promise<BigNumber>;

    updateCurrencyManager(
      _currencyManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateExecutionManager(
      _executionManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    WETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelAllOrdersForSender(
      minNonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelMultipleMakerOrders(
      orderNonces: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currencyManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    executionManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUserOrderNonceExecutedOrCancelled(
      user: PromiseOrValue<string>,
      orderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    matchAskWithTakerBid(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    matchAskWithTakerBidUsingETHAndWETH(
      takerBid: OrderTypes.TakerOrderStruct,
      makerAsk: OrderTypes.MakerOrderStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    matchBidWithTakerAsk(
      takerAsk: OrderTypes.TakerOrderStruct,
      makerBid: OrderTypes.MakerOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    royaltyFeeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferSelectorNFT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateCurrencyManager(
      _currencyManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateExecutionManager(
      _executionManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyFeeManager(
      _royaltyFeeManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateTransferSelectorNFT(
      _transferSelectorNFT: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    userMinOrderNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
