/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface RoyaltyFeeSetterInterface extends utils.Interface {
  functions: {
    "INTERFACE_ID_ERC1155()": FunctionFragment;
    "INTERFACE_ID_ERC2981()": FunctionFragment;
    "INTERFACE_ID_ERC721()": FunctionFragment;
    "checkForCollectionSetter(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "royaltyFeeRegistry()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateOwnerOfRoyaltyFeeRegistry(address)": FunctionFragment;
    "updateRoyaltyFeeLimit(uint256)": FunctionFragment;
    "updateRoyaltyInfoForCollection(address,address,address,uint256)": FunctionFragment;
    "updateRoyaltyInfoForCollectionIfAdmin(address,address,address,uint256)": FunctionFragment;
    "updateRoyaltyInfoForCollectionIfOwner(address,address,address,uint256)": FunctionFragment;
    "updateRoyaltyInfoForCollectionIfSetter(address,address,address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "INTERFACE_ID_ERC1155"
      | "INTERFACE_ID_ERC2981"
      | "INTERFACE_ID_ERC721"
      | "checkForCollectionSetter"
      | "owner"
      | "renounceOwnership"
      | "royaltyFeeRegistry"
      | "transferOwnership"
      | "updateOwnerOfRoyaltyFeeRegistry"
      | "updateRoyaltyFeeLimit"
      | "updateRoyaltyInfoForCollection"
      | "updateRoyaltyInfoForCollectionIfAdmin"
      | "updateRoyaltyInfoForCollectionIfOwner"
      | "updateRoyaltyInfoForCollectionIfSetter"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC1155",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC2981",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INTERFACE_ID_ERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkForCollectionSetter",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyFeeRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOwnerOfRoyaltyFeeRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyFeeLimit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyInfoForCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyInfoForCollectionIfAdmin",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyInfoForCollectionIfOwner",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRoyaltyInfoForCollectionIfSetter",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC2981",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INTERFACE_ID_ERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkForCollectionSetter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyFeeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOwnerOfRoyaltyFeeRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyFeeLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyInfoForCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyInfoForCollectionIfAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyInfoForCollectionIfOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRoyaltyInfoForCollectionIfSetter",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RoyaltyFeeSetter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RoyaltyFeeSetterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<[string]>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<[string]>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<[string]>;

    checkForCollectionSetter(
      collection: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateOwnerOfRoyaltyFeeRegistry(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyFeeLimit(
      _royaltyFeeLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyInfoForCollection(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyInfoForCollectionIfAdmin(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyInfoForCollectionIfOwner(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRoyaltyInfoForCollectionIfSetter(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

  INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<string>;

  INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

  checkForCollectionSetter(
    collection: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, number]>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  royaltyFeeRegistry(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateOwnerOfRoyaltyFeeRegistry(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyFeeLimit(
    _royaltyFeeLimit: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyInfoForCollection(
    collection: PromiseOrValue<string>,
    setter: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyInfoForCollectionIfAdmin(
    collection: PromiseOrValue<string>,
    setter: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyInfoForCollectionIfOwner(
    collection: PromiseOrValue<string>,
    setter: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRoyaltyInfoForCollectionIfSetter(
    collection: PromiseOrValue<string>,
    setter: PromiseOrValue<string>,
    receiver: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<string>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<string>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<string>;

    checkForCollectionSetter(
      collection: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, number]>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOwnerOfRoyaltyFeeRegistry(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyFeeLimit(
      _royaltyFeeLimit: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyInfoForCollection(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyInfoForCollectionIfAdmin(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyInfoForCollectionIfOwner(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRoyaltyInfoForCollectionIfSetter(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    INTERFACE_ID_ERC1155(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC2981(overrides?: CallOverrides): Promise<BigNumber>;

    INTERFACE_ID_ERC721(overrides?: CallOverrides): Promise<BigNumber>;

    checkForCollectionSetter(
      collection: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    royaltyFeeRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateOwnerOfRoyaltyFeeRegistry(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyFeeLimit(
      _royaltyFeeLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyInfoForCollection(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyInfoForCollectionIfAdmin(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyInfoForCollectionIfOwner(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRoyaltyInfoForCollectionIfSetter(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    INTERFACE_ID_ERC1155(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC2981(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    INTERFACE_ID_ERC721(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkForCollectionSetter(
      collection: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    royaltyFeeRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateOwnerOfRoyaltyFeeRegistry(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyFeeLimit(
      _royaltyFeeLimit: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyInfoForCollection(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyInfoForCollectionIfAdmin(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyInfoForCollectionIfOwner(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRoyaltyInfoForCollectionIfSetter(
      collection: PromiseOrValue<string>,
      setter: PromiseOrValue<string>,
      receiver: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
